#version: "3.9"  # version

services:  # all services
  web:  # app service
    build:  # Dockerfile
      context: .  # where locating
      dockerfile: Dockerfile  # what name for this file
    container_name: "web"  # name service (container)
    ports:  # service (container) ports
      - "8000:8000"
    logging:  # service (container) logs
      options:  # option for log
        max-size: '500M'  # max size log files
        max-file: '5'  # max count of files
    env_file:  # .env file with environments
      - ./.env
    command: uvicorn app:app --host localhost --port 8001 --reload # command for start work
    restart: always  # always restart service (container) if his breakdown
    volumes:  # connection your app's with workdir of service (container)
      - .:/app
    depends_on:  # what services (containers) this container depends on
      - mongodb
      - kafka

  mongodb: # mongodb service
    image: mongo:latest  # what image use for this service (container)
    container_name: "web-db"   # service (container) name
    env_file:  # .env file with environments
      - ./.env
    restart: always  # always restart service (container) if his breakdown
    ports:  # service (container) ports
      - "27017:27017"
#    volumes:  # connection your app's with workdir of service (container)
#      - type: bind
#        source: ./data
#        target: /data/db

  zookeeper:  # zookeeper service
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper  # hostname
    container_name: "zookeeper"  # service (container) name
    environment:  # environments for that service (container)
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:  # kafka service
    image: confluentinc/cp-kafka:latest
    container_name: "web-broker"  # service (container) name
    ports:  # service (container) ports
      - "9092:9092"
    env_file: # .env file with environments
      - ./.env
    depends_on:  # what services (containers) this container depends on
      - zookeeper
